### ISSUE TITLE
Time seek wraps around beginning and ending

### ISSUE THREAD

**Issue by airabinovich** [lettier/movie-monad#11]
It's awesome you included the feature I asked for, thanks! But to help improving your video player I want to report this issue

Given I'm playing a video
And time is at 0:05 
When I press left arrow to go back in time
Then the time goes to the near-end of the video

Same behavior is shown when I go to forward near the end, I go back to the near-beginning

**Comment by lettier** [comment]
Hello @airabinovich,

Yes this is the intended effect.

![video-seek-wrap](https://user-images.githubusercontent.com/1661343/34367981-43d2d0d0-ea7e-11e7-84ae-59cc7f3ea55c.png)


Say the video is `Y` time long and going backwards once would put it at time `00:00 - X` then the slider position is put at `Y - X`. 

Would you rather it truncate to 00:00?

:+1:

**Comment by airabinovich** [comment]
Hi @lettier,

As I see it, you can accidentially jump to the near-end of a video and watch some part you shouldn't have watched yet (spoilers)
I'd truncate the time seek at 00:00 and at `Y`as well. (Being `Y` the video length)

On another matter, I believe the time seek step is a portion of `Y`. I'd rather make it a fixed length (10 seconds I think is a good span)

**Comment by lettier** [comment]
Hello @airabinovich,

I changed the functionality to now stop at the beginning when seeking left and to stop at the end when seeking right.

I also reduced the step size for a more granular experience.

You can try out the pre-release [here](https://github.com/lettier/movie-monad/releases/download/0.0.4.0/movie-monad-0.0.4.0-x86_64.AppImage).

:+1:

**Comment by airabinovich** [comment]
It looks good to me now, great!
