### ISSUE TITLE
Doesn't support subtitles

### ISSUE THREAD

**Issue by hrqmonteiro** [lettier/movie-monad#16]
I can't find ANYWHERE how to setup the subtitles on an archive, it just doesn't support, there's nothing i can do, but even though you write on the description that it DOES support

I tried dragging the srt file, i tried opening a menu or something by cliicking the right button, and nothing works, nothing

**Comment by lettier** [comment]
Hello @hrqmonteiro 

Movie Monad supports subtitle tracks found inside the media container.

If your video doesn't have subtitle tracks, you can do something like this.

```bash
# https://mkvtoolnix.download/doc/mkvmerge.html
mkvmerge -o video-with-subtitles.mkv video.ext --default-language lang subtitles.srt
```
Where `ext` is the extension of your video and `lang` is the language of the subtitles. 

```bash
mkvmerge --list-languages
```

This will give you a list of supported languages. Be sure to use the `ISO639-2 code` for `lang`. So for example.

```bash
mkvmerge -o video-with-subtitles.mkv video.webm --default-language eng subtitles.srt
```

You can now open `video-with-subtitles.mkv` with Movie Monad and select the added subtitle track.

![test](https://user-images.githubusercontent.com/1661343/63657356-e0998c00-c76e-11e9-8089-764f3b6ea638.gif)

![test1](https://user-images.githubusercontent.com/1661343/63657358-e55e4000-c76e-11e9-9218-34988da9d173.gif)

:+1:

**Comment by hrqmonteiro** [comment]
Ok, so it doesn't support srt files, like all of the players in the world?
Everytime i want to watch a movie i would have to make this process of merging? Ok thanks for clarifying..
