### ISSUE TITLE
movie-monad doesn't find gst-plugins-bad

### ISSUE THREAD

**Issue by AsterLenas** [lettier/movie-monad#19]
Despite having the plugins installed (version 1.16.2) i get the following error message, `"gtksink" not found. No videos will show. Install the GStreamer 1.0 bad plugins version 1.8 or higher`

**Comment by lettier** [comment]
Hello,

I believe the [gst-plugin-gtk](https://www.archlinux.org/packages/extra/x86_64/gst-plugin-gtk/) now provides `gtksink`.

:+1:

**Comment by AsterLenas** [comment]
alrighty that fixed it, another dependency that showed itself after that was `gst-libav`, which seems to be needed to actually show the visual part of videos.

i modified the according line in the PKGBUILD on my system, it would look like this for the runtime dependencies:
`depends=("gtk3" "gstreamer" "gst-plugins-base-libs" "gst-plugins-base" "gst-plugins-good" "gst-plugin-gtk" "gst-libav" "gobject-introspection-runtime")` also tested it

Addedendum: the dependency of issue 18 is also included
