### ISSUE TITLE
Configuration in haskell?

### ISSUE THREAD

**Issue by riaqn** [lettier/movie-monad#2]
Thank you for this original work!

I was thinking, since this player is written in Haskell, which is very powerful and perfect fit for configuration, can we make the configuration in Haskell and make it VERY flexible? I haven't checked with the source code yet so I don't know how it can be done.

It could be something like xmonad. Key binding, video/audio decoding/filter, subtitle searching, or even theme/icon, could be configured in a Haskell file.

**Comment by lettier** [comment]
Hello and thank you.

Yes I suppose it would be possible. :+1:
