### ISSUE TITLE
AppImage does not run out of the box

### ISSUE THREAD

**Issue by probonopd** [lettier/movie-monad#8]
The AppImage does not run on an Ubuntu 14.04 system out of the box:

```
(movie-monad:4): Gtk-WARNING **: Failed to set property GtkButtonBox.layout-style to expand: Could not parse enum: `expand'
Could not create a GtkSink. Please install the bad plugins, version 1.8 or higher, for GStreamer 1.
movie-monad: Maybe.fromJust: Nothing
Parent pid 7340, child pid 7344
```

It would be nice if it would at least run, then show a GUI dialog instructing the user what to do. Alternatively, could attempt to bundle GStreamer and the required plugins inside the AppImage.

Reference:
https://travis-ci.org/AppImage/appimage.github.io/builds/294387373#L711-L713

**Comment by lettier** [comment]
Hello @probonopd 

The GUI window will still proceed to open even if the plugins are not found. That message is just sent to standard out before the window opens. You can see this happening in the screenshot below.

![screenshot_2017-10-29_05-54-22](https://user-images.githubusercontent.com/1661343/32142445-a8d62160-bc6d-11e7-9bb0-fc2ba84f0aa5.png)

And then, as you suggested, it will display a dialog box explaining the situation when the user attempts to play a video.

![screenshot_2017-10-29_05-59-10](https://user-images.githubusercontent.com/1661343/32142484-5c001d40-bc6e-11e7-8a7c-e1cc0fbad3a1.png)

Still, I haven't given up on bundling the dependencies as we discussed in https://github.com/lettier/movie-monad/issues/5. Hoping to tackle this soon.

:+1:

**Comment by probonopd** [comment]
Thank you very much for the heads-up. Somehow my automated test script doesn't find any window on the screen but I guess I need to figure out why this is.
